# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4202334843bd831ce1e4a7d46833f4641b2771dd6be41bc4e810015b0fb1b7247783274bffdc1dd9173741765f260550f3dd1987094cd9aaf523f45693c12ae4

test:
  secret_key_base: cb0c012845cda7e91ee0570552e35daa9ff031d29a3c744c3d453328a54fd99ecaa806d32d13b8690752bbd2f995435f78d43833e8e3cc5df40900bf3b528865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
