source 'https://rubygems.org'

gem 'thinking-sphinx', '3.0.0'
gem 'less-rails-bootstrap'
gem 'therubyracer'
gem 'twitter-bootstrap-rails'
gem 'rails', '4.1.2'
gem 'pg'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development


group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'factory_girl_rails', '~> 4.0'
end

group :test do
  gem 'capybara', '~>2.0.2'
  gem 'guard'
  gem 'guard-rspec'
  gem 'growl'
end