source 'https://rubygems.org'
ruby '2.1.2'

gem 'rails', '4.1.5'
gem 'jquery-rails', "~> 2.3.0"
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'bootstrap-sass', '~> 3.0.3.0'
gem 'spring',        group: :development
gem "paperclip", github: 'thoughtbot/paperclip'


group :production do
	gem 'pg'
	gem 'rails_12factor'
end

group :development  do
	gem 'sqlite3'
end

group :doc do
  gem 'sdoc', require: false
end