# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dce49b293fd48a0f9c27d311cf4f836dcf3ea1be5e316a981b6c098c10e15f3d287b4066d676baa577c26db6606965dcce4b9e0a964b651abd43b64375924601

test:
  secret_key_base: 48c7009d6fcbd8809f66b095a8ea15a1c697e0d40ebcc9a8754d3aad25352061819f843ce32e04fd64bf7fae454a6c1f0659e5fdc5fbba12f110feb3ca39a6d8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
